[project]
name = "comp-capacity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "polars>=1.27.1",
    "seaborn>=0.13.2",
    "torch>=2.6.0",
]

[project.optional-dependencies]
dev = [
    "ipykernel>=6.29.5",
]
